### ISSUE TITLE
Geração de um segredo criptográfico a partir de palavras-passe inseridas pelo utilizador

### ISSUE THREAD

**Issue by PedroCavaleiro** [PedroCavaleiro/XIUUUU#2]
> Geração de um segredo criptográfico a partir de palavras-passe inseridas pelo utili- zador, nomeadamente através de algoritmos como o Password Based Key Derivation Function 2 (PBKDF2)

**Comment by Jose-Pires** [comment]
# O que é ?

O _PBKDF2_ (_Password Based Key Derivation Function 2_) é um algoritmo feito por design para ser lento e com o intuito de reduzir a vulnerabilidade de segredos criptográficos a "ataques de força bruta". Descendente do _PBKDF1_ apenas gera chaves de um tamanho máximo de 160 _bits_.

## Funcionamento:

No _PBKDF2_ são aplicadas funções "pseudo-randomizadas" como o _HMAC_ (_Hash-based message authentication code_), ela recebe como input a password, uma sequência randomizada de _bits_ denominada de _salt_ de qualquer tamanho (normalmente de  64 _bits_), ela repete o processo _x_ vezes até se produzir uma _derived key_ . Este processo é também denominado de _key stretching_.

### Exemplo:

A função PBKDF2 recebe 5 parâmetros:

> DK = PBKDF2(PRF, Password, Salt, c, dkLen)

- _PRF_ é a função de "pseudo-randomização" com dois parâmetros de entrada, a _Password_ e o _Salt_ (e.g. _HMAC_);
- _Password_ é o segredo a ser protegido;
- _Salt_ é a sequência randomizada de _bits_;
- _c_ é o número de iterações desejadas;
- _dkLen_ é o tamanho em bits desejado para a _derived key_;
- _DK_ é _derived key_ gerada.

(Nota:  Usando este exemplo como apoio, após a primeira iteração a password mantêm-se mas o _Salt_ é substituído pelo output da iteração anterior).

Para mais informação:
https://en.wikipedia.org/wiki/PBKDF2

Vou detalhar depois no próximo comentário o _HMAC_ e outras funções usadas no PBKDF2 .
Btw usei infelizmente o _Wikipedia_ para consultar a explicação disto porque infelizmente do que estive a ver noutros sites o conteúdo era pouco 😞
