### ISSUE TITLE
Troca de um segredo criptográfico usando o Rivest Shamir Adleman (RSA)

### ISSUE THREAD

**Issue by PedroCavaleiro** [PedroCavaleiro/XIUUUU#5]
> Troca de um segredo criptográfico usando o Rivest Shamir Adleman (RSA)

**Comment by pedroBatis96** [comment]
Dos pdfs do stor, resumindo (encontra-se no lecture 5 pag 5 e 6)

-RSA é usado para referir um sistema de cifrade chave pública
![rsa](https://user-images.githubusercontent.com/39657995/47257428-84e2e000-d485-11e8-99f4-380799a41716.png)

-A segurança do RSA está dependente do facto da função F(pf; x) ser de sentido único sem o alçapão sk.

Não se deve usar a permutação RSA para cifrar mensagens
diretamente.

Devemos usar RSA em conjunção com o OAEP (RSA-OAEP) 
lecture 5 pag 6


O lab dedicado ao RSA é o lab 8

https://en.wikipedia.org/wiki/RSA_(cryptosystem)#Key_generation

fiquei ainda um pouco confuso com o RSA mas acho que todos juntos conseguimos ver isto melhor e com mais detalhes, mas pelo que entendo temos de gerar uma chave publica e privada, os utilizadores terem acesso a publica e o agente de confiança à privada
